GRANT ALL PRIVILEGES ON DATABASE spbasket TO spbasket_user;
\c spbasket
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO spbasket_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO spbasket_user;
